# -*- coding: utf-8 -*-
"""t2 votes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G-cy9ihv9MdSdP-WR70rRlxf77Q_MtDs
"""

import csv

file_path = "/content/election_data.csv"

total_votes = 0
candidates = {}
winner = ""
winner_votes = 0

with open(file_path, newline="") as csvfile:
    csvreader = csv.reader(csvfile, delimiter=",")

    next(csvreader)
    for row in csvreader:

        candidate = row[1]

        total_votes += 1

        if candidate in candidates:
            candidates[candidate] += 1
        else:
            candidates[candidate] = 1


print("Election Results")
print("-------------------------")
print(f"Total Votes: {total_votes}")
print("-------------------------")


for candidate, vote_count in candidates.items():
    vote_percentage = vote_count / total_votes * 100
    print(f"{candidate}: {vote_percentage:.3f}% ({vote_count})")

    if vote_count > winner_votes:
        winner = candidate
        winner_votes = vote_count


print("-------------------------")
print(f"Winner: {winner}")
print("-------------------------")